name: firebase_msg
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_core: ^2.24.0
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_storage:
  connectivity_plus: ^5.0.2
  email_validator: ^3.0.0
  intl: ^0.19.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  pinput: ^5.0.0
  aligned_dialog: ^0.0.7
  vibration: ^1.3.0
  google_sign_in: ^6.2.1
  email_otp: ^3.0.2
  google_nav_bar: 5.0.6
  google_fonts: ^6.2.1
  rive_animated_icon: ^2.0.0
  emoji_picker_flutter: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
